- id: tartufo
  name: Tartufo
  description: '`tartufo` is a tool for scanning git repositories for secrets/passwords/high-entropy data'
  entry: tartufo
  language: python
  args: [--cleanup, pre-commit]
  pass_filenames: false
