version: 2

build:
  image: latest

formats: all

sphinx:
  configuration: docs/source/conf.py

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
